- name: Create Webapi load balancer
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/region.yml
  
  tasks:
    - name: Create load balancer 
      ec2_elb_lb:
        region: "{{ ec2_region }}"
        name: "WebApi-LoadBalancer"
        scheme: internet-facing
        state: present
        connection_draining_timeout: 10
        cross_az_load_balancing: yes
        security_group_names: webapi_lb_sg
        idle_timeout: 4000
        subnets:
          - subnet-b6feeeec
          - subnet-f97bc39d
        listeners:
        - protocol: http
          load_balancer_port: 8080
          instance_port: 8080
#        - protocol: https
#          load_balancer_port: 443
#          instance_protocol: http 
#          instance_port: 8080
#           ssl_certificate_id:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
        - protocol: TCP
          load_balancer_port: 22
          instance_port: 22
        health_check:
          ping_protocol: tcp
          ping_port: 22
#          ping_path: "/monitoring/health"
          response_timeout: 5
          interval: 30
          unhealthy_threshold: 2
          healthy_threshold: 3 
        access_logs:
          interval: 5
          s3_location: "martin-loadbalancer-logs"
          s3_prefix: "web-app"
