- name:  Configure webapi server
  hosts: WebApi-LoadBalancer-1200527156.us-east-1.elb.amazonaws.com,
  become: yes
  become_method: sudo 
  gather_facts: True

  vars_files:
    - ../vars/region.yml  


  tasks:
  - name: Change hostname
    hostname: 
      name: webapi1

  - name: add hostname to /etc/hosts
    lineinfile:
      dest=/etc/hosts
      line='127.0.1.1 webapi1'
      regexp='^127\.0\.1\.1'
      insertafter='^127\.0\.0\.1'
      state=present

  - name: Network | Add domain suffix to dhclient.conf
    lineinfile: dest=/etc/dhcp/dhclient.conf
      backup=yes
      state=present
      regexp='^supersede domain-name'
      line="supersede domain-name \"{{ martin_domain_name }}\";"
    register: domainname

  - name: Network | Add domain search to dhclient.conf
    lineinfile: dest=/etc/dhcp/dhclient.conf
      backup=yes
      state=present
      regexp='^supersede domain-search'
      line="supersede domain-search \"{{ martin_domain_name }}\";"
    register: domainsearch

  - name: Network | Run dhclient to change domain
    command: dhclient

  - name: Network | Restart network
    command: bash -c "ifdown eth0 && ifup eth0"
    when: (domainname.changed) or
          (domainsearch.changed)
